/**
 * `setup_flow_scaffold_profile` (C4). Renders `.pi/flow.profile.md` from
 * the canonical body template (`extension/skills/setup-flow/profile-
 * template.md`) plus a YAML frontmatter block synthesised from the
 * wizard's answers. The wizard (C5) collects the answers; this tool is
 * the pure write step.
 *
 * The label vocabulary in the frontmatter is derived from `labels.md`
 * (the same source of truth `setup_flow_apply_labels` uses), so the
 * profile can never disagree with what's actually on the repo. The
 * answers object may override individual state labels via
 * `labelOverrides`.
 *
 * No commit — the file is left in the working tree.
 *
 * Round-trip guarantee: the file we write parses cleanly via
 * `readProfile` from `profile.ts`, and `labels.state` covers every key
 * `profile.ts` declares as required.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { stringify as yamlStringify } from "yaml";
import { parseLabelsMarkdown, type LabelSpec } from "./setup-labels.ts";

// --- Defaults -------------------------------------------------------------

export const DEFAULT_AI_DISCLAIMER =
  "> *This was generated by AI during triage.*";
export const DEFAULT_VERIFY_GATE =
  'echo "verify-gate: default-pass (not yet implemented)"';
export const DEFAULT_IN_SITU_HARNESS =
  "<e.g. a CDP/dev harness for UI-bearing slices>";
export const DEFAULT_REVIEWER_COMMAND = "/code-review";
export const DEFAULT_REVIEWER_ITERATION_CAP = 2;
export const DEFAULT_POLL_CADENCE_SECONDS = 30;
export const DEFAULT_TRACK_BRANCH_PREFIX = "track/";

/**
 * Canonical state keys, in the order `profile.ts` declares them. We map
 * each one to its default label name by replacing underscores with
 * dashes — the convention `labels.md` already follows. The `answers`
 * object can override any of these per-key.
 */
const STATE_KEYS = [
  "needs_triage",
  "needs_info",
  "needs_grilling",
  "needs_slicing",
  "needs_plan_review",
  "tracking",
  "ready_for_agent",
  "ready_for_human",
  "needs_acceptance",
  "wontfix",
] as const;
type StateKey = (typeof STATE_KEYS)[number];

function defaultStateLabel(key: StateKey): string {
  return key.replace(/_/g, "-");
}

// --- Public shapes --------------------------------------------------------

export type ScaffoldAnswers = {
  owner: string;
  repo: string;
  defaultBranch: string;
  trackBranchPrefix?: string;
  verifyGate?: string;
  inSituHarness?: string;
  reviewerCommand?: string;
  reviewerIterationCap?: number;
  pollCadenceSeconds?: number;
  aiDisclaimer?: string;
  /** Override a state-key → label string. Unknown keys are ignored. */
  labelOverrides?: Record<string, string>;
};

export type ScaffoldResult =
  | { written: true; path: string }
  | { written: false; path: string; reason: "exists" };

export type ScaffoldProfileFs = {
  exists(path: string): boolean;
  mkdirp(path: string): void;
  writeFile(path: string, contents: string): void;
};

export type ScaffoldProfile = {
  run(
    answers: ScaffoldAnswers,
    opts?: { overwrite?: boolean },
  ): Promise<ScaffoldResult>;
};

// --- Frontmatter builder --------------------------------------------------

/**
 * Build the frontmatter object that round-trips through `readProfile`.
 * Pure — no I/O. Exposed for the smoke test.
 *
 * `labelOverrides` is applied **on top of** the defaults: missing keys
 * fall through to `defaultStateLabel(key)`. Effort + review + category
 * labels are derived from `canonical` (the parsed `labels.md`) by
 * pattern-matching on prefix — kept narrow because the canonical set is
 * fixed by the labels file and `setup_flow_apply_labels` enforces it.
 */
export function buildFrontmatter(
  answers: ScaffoldAnswers,
  canonical: LabelSpec[],
): Record<string, unknown> {
  const names = new Set(canonical.map((c) => c.name));
  const overrides = answers.labelOverrides ?? {};

  const state: Record<string, string> = {};
  for (const k of STATE_KEYS) {
    state[k] = overrides[k] ?? defaultStateLabel(k);
  }

  const category = canonical
    .map((c) => c.name)
    .filter((n) => n === "bug" || n === "enhancement");

  function pickByPrefix(prefix: string): string[] {
    return [...names].filter((n) => n.startsWith(prefix));
  }
  const effortNames = pickByPrefix("effort:");
  const reviewNames = pickByPrefix("review:");

  function effort(level: "low" | "medium" | "high"): string {
    const want = `effort:${level}`;
    return effortNames.includes(want) ? want : want;
  }
  function review(side: "agent" | "human"): string {
    const want = `review:${side}`;
    return reviewNames.includes(want) ? want : want;
  }

  return {
    tracker: "github",
    repo: `${answers.owner}/${answers.repo}`,
    default_branch: answers.defaultBranch,
    track_branch_prefix:
      answers.trackBranchPrefix ?? DEFAULT_TRACK_BRANCH_PREFIX,
    verify_gate: answers.verifyGate ?? DEFAULT_VERIFY_GATE,
    in_situ_harness: answers.inSituHarness ?? DEFAULT_IN_SITU_HARNESS,
    reviewer_command: answers.reviewerCommand ?? DEFAULT_REVIEWER_COMMAND,
    reviewer_iteration_cap:
      answers.reviewerIterationCap ?? DEFAULT_REVIEWER_ITERATION_CAP,
    poll_cadence_seconds:
      answers.pollCadenceSeconds ?? DEFAULT_POLL_CADENCE_SECONDS,
    ai_disclaimer: answers.aiDisclaimer ?? DEFAULT_AI_DISCLAIMER,
    labels: {
      category: category.length > 0 ? category : ["bug", "enhancement"],
      state,
      effort: {
        low: effort("low"),
        medium: effort("medium"),
        high: effort("high"),
      },
      review: {
        agent: review("agent"),
        human: review("human"),
      },
    },
  };
}

/**
 * Render the full profile markdown: YAML frontmatter + the canonical
 * template body, untouched. Pure.
 */
export function renderProfile(
  answers: ScaffoldAnswers,
  canonical: LabelSpec[],
  templateBody: string,
): string {
  const fm = buildFrontmatter(answers, canonical);
  // `yaml@2` defaults emit unquoted plain scalars where safe; that
  // matches the round-trip target shape.
  const yaml = yamlStringify(fm).trimEnd();
  // The template body already contains a leading `<!-- comment -->` and
  // an `# Flow profile` heading — separate frontmatter from it with a
  // single blank line.
  return `---\n${yaml}\n---\n\n${templateBody.replace(/^\s+/, "")}`;
}

// --- Factory --------------------------------------------------------------

export const PROFILE_REL_PATH = ".pi/flow.profile.md";

export function createScaffoldProfile(deps: {
  cwd: string;
  fs: ScaffoldProfileFs;
  loadTemplateBody: () => string;
  loadCanonicalLabelsMd: () => string;
}): ScaffoldProfile {
  return {
    async run(answers, opts = {}) {
      const path = join(deps.cwd, PROFILE_REL_PATH);
      if (deps.fs.exists(path) && !opts.overwrite) {
        return { written: false, path, reason: "exists" };
      }
      const canonical = parseLabelsMarkdown(deps.loadCanonicalLabelsMd());
      const body = deps.loadTemplateBody();
      const rendered = renderProfile(answers, canonical, body);
      deps.fs.mkdirp(dirname(path));
      deps.fs.writeFile(path, rendered);
      return { written: true, path };
    },
  };
}

// --- Production wiring ----------------------------------------------------

export function defaultLoadTemplateBody(cwd: string): () => string {
  const p = join(cwd, "extension", "skills", "setup-flow", "profile-template.md");
  return () => readFileSync(p, "utf8");
}

export function defaultScaffoldFs(): ScaffoldProfileFs {
  return {
    exists: (p) => existsSync(p),
    mkdirp: (p) => mkdirSync(p, { recursive: true }),
    writeFile: (p, c) => writeFileSync(p, c, "utf8"),
  };
}
